110 convert qml menu
Sage-Cat/SageStore pull request #22
Opened 2024-02-18 17:56 UTC by momotav

2024-02-18 18:04 UTC, Sage-Cat requested changes

2024-02-18 18:04 UTC, Sage-Cat commented on _client/src/Views/Actions.hpp
> +enum class ActionTypes {
Make namespace Actions
And change this enum and map names to Types and NAMES

2024-02-19 19:30 UTC, Sage-Cat approved these changes
LGTM

2024-02-19 19:32 UTC, DanyloPlotskykh approved these changes
OMG!!! This is the pritiest code i'd ever seen!!!

2024-02-19 19:34 UTC, merged