131 implement api
Sage-Cat/SageStore pull request #28
Opened 2024-03-05 21:58 UTC by DanyloPlotskykh

2024-03-10 21:10 UTC, Sage-Cat requested changes

2024-03-10 21:10 UTC, Sage-Cat commented on _client/src/Network/ApiManager.cpp
> +    dataset["newRole"] = {newRole};
`newRole` -> `roleName`

2024-03-10 21:10 UTC, Sage-Cat commented on _client/src/Network/ApiManager.cpp
> +        handleRolesResponse(method, dataset);
Refactor **to have switch and to keep unique signal per request**.

Rename this and signals also
```cpp
   virtual void getRolesList();
    virtual void createNewRole(const QString &roleName);
    virtual void editRole(const QString &id, const QString &roleName);
    virtual void deleteRole(const QString &id);
```

signals:
```cpp
    void rolesList(QList<Role>);
    void newRoleCreated();
    void roleEdited();
    void roleDeleted();
```

2024-03-10 21:10 UTC, Sage-Cat commented on _client/src/Network/ApiManager.cpp
> +void ApiManager::editRole(const QString &id, const QString &role_name)
Code name convention (CamelCase): `roleName`

2024-03-10 21:10 UTC, Sage-Cat commented on _client/src/Network/ApiManager.hpp
> +    handleResponse(const QString &endpoint, Method method, const Dataset &dataset);
return back

2024-03-10 21:10 UTC, Sage-Cat commented on _client/src/Network/ApiManager.hpp
> +    void handleGetRolesResponse(Method method, const Dataset &dataset);
You don't need this methods at all.
Just keep it `handleRoles` and do inside switch case to perform all necessary emits of signals

2024-03-10 21:10 UTC, Sage-Cat commented on _client/src/Network/NetworkService.hpp
> +    DELETES = QNetworkAccessManager::Operation::DeleteOperation
Just `DELETE`

2024-03-10 21:10 UTC, Sage-Cat commented on _client/tests/mocks/ApiManagerMock.hpp
> +    }
\+ space

2024-03-10 21:10 UTC, Sage-Cat commented on _client/tests/unit/ApiManagerTest.cpp
> +    }
\+ space

2024-03-11 18:46 UTC, Sage-Cat requested changes

2024-03-11 18:46 UTC, Sage-Cat commented on _client/src/Network/ApiManager.cpp
> +    dataset["editRole"] = {roleName};
roleName

2024-03-11 18:46 UTC, Sage-Cat commented on _client/src/Network/ApiManager.cpp
> +    Dataset dataset;
remove dataset (it's not needed in get and delete methods)

2024-03-11 18:46 UTC, Sage-Cat commented on _client/src/Network/ApiManager.cpp
> +    QMap<QString, ApiManager::ResponseHandler>::const_iterator handler = m_responseHandlers.cend();
What's the point of this? Remove it and return back my code

2024-03-11 18:46 UTC, Sage-Cat commented on _client/src/Network/ApiManager.hpp
> +    void rolesList(const Dataset &dataset);
Not dataset. Create empty `struct Role{}` and send QVector<Role> via signal

2024-03-12 15:04 UTC, VolodymyrBilenko commented on _client/src/Network/ApiManager.cpp
> +    for (auto i = idList.cbegin(), j = nameList.cbegin(); i != idList.cend(); i++, j++)
Please do not use i, j. All variables should have meaningful names

2024-03-12 15:27 UTC, VolodymyrBilenko requested changes

2024-03-12 15:27 UTC, VolodymyrBilenko commented on _client/src/Network/ApiManager.cpp
> +        Role role(((i)->isEmpty() ? "" : *i), ((j)->isEmpty() ? "" : *j));
Please avoid implicit statements such as ternary operator. It complicates code reading.
Better to create variable that would hold result of comparison and then create Role. 
Anyway compiler will optimize it and there would be no difference in assembler code.

2024-03-12 15:27 UTC, VolodymyrBilenko commented on _client/src/Network/ApiManager.hpp
> +    Role(QString id, QString name) : id{id},
input parameters should be of constant type and passed through reference

2024-03-12 15:27 UTC, VolodymyrBilenko commented on _client/src/Network/NetworkService.cpp
> +    // (resource_id == "") ? fullUrl = m_apiUrl + endpoint : fullUrl = m_apiUrl + endpoint + "/" + resource_id;
no commented out code shall be present

2024-03-12 21:24 UTC, Sage-Cat requested changes

2024-03-12 21:24 UTC, Sage-Cat commented on _client/src/Network/ApiManager.cpp
> +        dataset,
use {} to init default dataset

2024-03-12 21:24 UTC, Sage-Cat commented on _client/src/Network/ApiManager.cpp
> +    dataset["roleName"] = {roleName};
Sorry, my bad explanation, it should be not roleName but `Keys::Role::NAME`

2024-03-12 21:24 UTC, Sage-Cat commented on _client/src/Network/ApiManager.cpp
> +void ApiManager::handleRoleList(const Dataset &dataset)
this method is something...
refactor it completly

do something like this
```cpp
try {
    QVector<Role> roles;

    const auto& idList = dataset.at(Keys::Role::ID);
    const auto& nameList = dataset.at(Keys::Role::NAME);

    if (idList.size() != nameList.size()) {
        throw std::runtime_error("ID list and Name list have different sizes.");
    }

    roles.reserve(idList.size());

    for (int i = 0; i < idList.size(); ++i) {
        roles.push_back(Role(idList[i], nameList[i]));
    }
} catch (const std::exception& e) {
    handleError(e.what());
}
```

2024-03-12 21:30 UTC, Sage-Cat requested changes

2024-03-12 21:30 UTC, Sage-Cat commented on _client/src/Network/NetworkService.cpp
> +    QUrl fullUrl{m_apiUrl + endpoint + "/" + resource_id};
@VolodymyrBilenko needs refactoring.

We could just overload this method to have different params or separate responsibility of creating url to different overloaded methods.

2024-03-12 21:30 UTC, Sage-Cat commented on _server/tests/CMakeLists.txt
> +# add_subdirectory(unit)
?
Remove this.

2024-03-12 21:39 UTC, VolodymyrBilenko requested changes, later dismissed

2024-03-12 21:39 UTC, VolodymyrBilenko commented on _client/src/Network/ApiManager.cpp
> +        if (!(id->isEmpty() && name->isEmpty()))
You call the same method isEmpty() for id and name several times in different if statement. I would recommend call them once before if(), store result in temporal variable and then use it for checks.

2024-03-12 21:39 UTC, VolodymyrBilenko commented on _client/src/Network/ApiManager.cpp
> +        QString strId = "", strName = "";
Please declare strName from new line.

2024-03-12 22:05 UTC, Sage-Cat requested changes

2024-03-12 22:05 UTC, Sage-Cat commented on _client/src/Network/ApiManager.cpp
> +        handleError("dataset doesen't contains ID or NAME");
doesn't

2024-03-12 22:05 UTC, Sage-Cat commented on _client/src/Network/ApiManager.hpp
> +    void newRoleCreated();
roleCreated

2024-03-12 22:05 UTC, Sage-Cat commented on _client/tests/mocks/NetworkServiceMock.hpp
> +        else if (endpoint.contains(Endpoints::Users::ROLES) != std::string::npos && method == Method::PUT)
now you can avoid using contains due to new sendRequest
they are soulb be just equal now

2024-03-12 22:12 UTC, Sage-Cat approved these changes

2024-03-13 17:38 UTC, Field-Effect-Transistor approved these changes
LGTM

2024-03-14 19:49 UTC, merged