Fixed
Sage-Cat/SageStore pull request #32
Opened 2024-03-11 03:20 UTC by MaksymDi1409

2024-03-11 03:26 UTC, Field-Effect-Transistor commented on _client/src/Network/ApiManager.cpp
> +       SPDLOG_DEBUG("ApiManager::handleResponse for endpoint={}", endpoint.toStdString());
remove tab

2024-03-11 18:32 UTC, Sage-Cat requested changes

2024-03-11 18:32 UTC, Sage-Cat commented on _client/src/Network/ApiManager.cpp
> +            for (const QString& errorMsg : errorMessages)
Did you tested this?

It will print two message boxes, but task asks you to print only one with second message on the new line

2024-03-11 18:32 UTC, Sage-Cat commented on _client/src/Network/ApiManager.cpp
> +       SPDLOG_DEBUG("ApiManager::handleResponse for endpoint={}", endpoint.toStdString());
what is this tabulation?

2024-03-23 17:42 UTC, Sage-Cat requested changes

2024-03-23 17:42 UTC, Sage-Cat commented on _client/src/Network/ApiManager.cpp
> +                errorMsg = "Unknown error format";
Why unknown format?

2024-03-23 17:42 UTC, Sage-Cat commented on _client/src/Network/ApiManager.cpp
> +             const QStringList& errorData = dataset[Keys::_ERROR];
identation (one space makes code ugly)

2024-03-23 17:42 UTC, Sage-Cat commented on _client/src/Network/ApiManager.cpp
> +                QString componentName = errorData[0];
Why not foreach cycle?

2024-03-23 17:42 UTC, Sage-Cat commented on _client/src/Network/ApiManager.cpp
> +                errorMsg = componentName + "\n" + errorMessage;
Use foreach, like this:
```c++
QString result{};
for (const auto &errorLine : dataset[Keys::_ERROR])
    result  += errorLine + "\n";
```

2024-03-23 20:36 UTC, Sage-Cat requested changes

2024-03-23 20:36 UTC, Sage-Cat commented on _client/src/Network/ApiManager.cpp
> +  SPDLOG_DEBUG("ApiManager::handleResponse for endpoint={}", endpoint.toStdString());
what's with tabulation?

2024-03-23 20:36 UTC, Sage-Cat commented on _client/src/Network/ApiManager.cpp
> +            errorMsg += errorData + "\n";
and here

Install clang extension and set setting "format on save"

2024-03-28 19:32 UTC, Sage-Cat requested changes

2024-03-28 19:32 UTC, Sage-Cat commented on _client/src/Network/ApiManager.cpp
> +
remove new line here

2024-03-28 19:32 UTC, Sage-Cat commented on _client/src/Network/ApiManager.cpp
> +        }
print new line after this

2024-03-28 19:32 UTC, Sage-Cat approved these changes

2024-03-28 19:34 UTC, DanyloPlotskykh approved these changes

2024-03-28 20:03 UTC, merged