138 bug
Sage-Cat/SageStore pull request #33
Opened 2024-03-11 03:52 UTC by Field-Effect-Transistor

2024-03-11 18:34 UTC, Sage-Cat requested changes

2024-03-11 18:34 UTC, Sage-Cat commented on _client/src/Utils.cpp
> +    //remove QLayout (not now)
remove comment (you can close thread after that yourself)

2024-03-11 18:35 UTC, Sage-Cat approved these changes

2024-03-12 08:06 UTC, MaksymDi1409 approved these changes
everything is fine

2024-03-12 08:07 UTC, MaksymDi1409 commented on _client/src/main.cpp
> -
Remove tab

2024-03-12 08:08 UTC, merged