inspector tool with registration and login
Sage-Cat/SageStore pull request #47
Opened 2024-06-22 07:51 UTC by Hokuto-no-Ken

### Changes 
Add login and registration form to inspect SageStoreServer.
  
### Testing
Login and registration work correctly , test in different usernames and passwords

Closes [SS-26](https://sageteam.atlassian.net/browse/SS-26)

2024-06-30 18:30 UTC, Sage-Cat commented
Change commit name and message. It should match our contibution guides
https://github.com/Sage-Cat/SageStore/blob/master/CONTRIBUTING.md#commit-messages

2024-06-30 18:30 UTC, Sage-Cat requested changes
Change commit name and message. It should match our contibution guides
https://github.com/Sage-Cat/SageStore/blob/master/CONTRIBUTING.md#commit-messages

2024-07-07 13:46 UTC, MaksGMaks approved these changes

2024-07-24 17:25 UTC, Sage-Cat approved these changes

2024-07-24 17:25 UTC, merged