112 base widget
Sage-Cat/SageStore pull request #5
Opened 2023-12-03 18:58 UTC by MaksGMaks

create base widget. need code review

2023-12-07 18:19 UTC, Sage-Cat requested changes

2023-12-07 18:19 UTC, Sage-Cat commented on _client/src/Ui/Component/BaseWidget.hpp
> +    QVBoxLayout *_mMainLayout = new QVBoxLayout(this);
m_mainLayout

2023-12-07 18:19 UTC, Sage-Cat commented on _client/src/Ui/Component/BaseWidget.hpp
> +    QHBoxLayout *_mButtonRow = new QHBoxLayout;
initialization to cpp

2023-12-07 18:19 UTC, Sage-Cat commented on _client/src/Ui/Component/BaseWidget.hpp
> +signals:
remove redudant

2023-12-07 18:19 UTC, Sage-Cat commented on _client/src/Ui/Component/BaseWidget.hpp
> +public slots:
remove

2023-12-07 18:19 UTC, Sage-Cat commented on _client/src/Ui/Component/BaseWidget.hpp
> +    QPushButton *_mEditButton = new QPushButton("Edit", this);
space

2023-12-07 18:19 UTC, Sage-Cat commented on _client/src/Ui/Component/BaseWidget.hpp
> +    QSpacerItem *_mAdditionalButtonSpace = new QSpacerItem(100, 50, QSizePolicy::Expanding, QSizePolicy::Fixed);
magic number

2023-12-07 18:19 UTC, Sage-Cat commented on _client/src/Ui/Component/BaseWidget.hpp
> +#ifndef BASEWIDGET_H
pragma once

2023-12-07 18:19 UTC, Sage-Cat commented on _client/src/Ui/Component/BaseWidget.hpp
> +    QSpacerItem *_mAdditionalUnderTableSpace = new QSpacerItem(100, 10, QSizePolicy::Expanding, QSizePolicy::Minimum);
ADDITIONAL_UNDER_TABLE_SPACE_WIDTH

2023-12-10 19:34 UTC, MaksGMaks commented on _client/src/Ui/Component/BaseWidget.hpp
> +    QVBoxLayout *_mMainLayout = new QVBoxLayout(this);
done

2023-12-10 19:38 UTC, MaksGMaks commented on _client/src/Ui/Component/BaseWidget.hpp
> +signals:
done

2023-12-10 19:38 UTC, MaksGMaks commented on _client/src/Ui/Component/BaseWidget.hpp
> +#ifndef BASEWIDGET_H
done, but not sure

2023-12-10 19:43 UTC, MaksGMaks commented on _client/src/Ui/Component/BaseWidget.hpp
> +    QPushButton *_mEditButton = new QPushButton("Edit", this);
can't make. fucking visual doesn't allow it

2023-12-10 19:46 UTC, MaksGMaks commented on _client/src/Ui/Component/BaseWidget.hpp
> +    QSpacerItem *_mAdditionalUnderTableSpace = new QSpacerItem(100, 10, QSizePolicy::Expanding, QSizePolicy::Minimum);
DONE

2023-12-13 18:17 UTC, Sage-Cat requested changes

2023-12-13 18:17 UTC, Sage-Cat commented on _client/src/Ui/Component/BaseWidget.hpp
> +    QVBoxLayout * m_MainLayout;
correct `QVBoxLayout  *m_mainLayout;`

2023-12-13 18:17 UTC, Sage-Cat commented on _client/src/Ui/Component/BaseWidget.hpp
> +    void setupUi();
virtual

2023-12-13 18:17 UTC, Sage-Cat commented on _client/src/Ui/Component/BaseWidget.hpp
> +    BaseWidget(QWidget *parent = nullptr);
add virtual destructor

2023-12-13 18:17 UTC, Sage-Cat commented on _client/src/Ui/Component/BaseWidget.hpp
> +    void setupUi();
protected

2023-12-13 18:20 UTC, Sage-Cat requested changes

2023-12-13 18:20 UTC, Sage-Cat commented on _client/src/Ui/Component/BaseWidget.hpp
> +const int ADDIT_SPACE_WIDTH = 100;
inside class
public

2023-12-18 13:13 UTC, MaksGMaks commented on _client/src/Ui/Component/BaseWidget.hpp
> +    BaseWidget(QWidget *parent = nullptr);
done

2023-12-18 13:13 UTC, MaksGMaks commented on _client/src/Ui/Component/BaseWidget.hpp
> +    void setupUi();
done

2023-12-18 13:14 UTC, MaksGMaks commented on _client/src/Ui/Component/BaseWidget.hpp
> +    void setupUi();
done

2023-12-18 13:16 UTC, MaksGMaks commented on _client/src/Ui/Component/BaseWidget.hpp
> +    QVBoxLayout * m_MainLayout;
done

2023-12-18 17:45 UTC, Sage-Cat requested changes

2023-12-18 17:45 UTC, Sage-Cat commented on _client/src/Constants.cpp
> +const int ADDIT_SPACE_WIDTH = 100;
Add namespace with good name

2023-12-18 17:45 UTC, Sage-Cat commented on _client/src/Constants.cpp
Set better filename for spesific scope, like `WidgetStyles.hpp" or smth

**And it should be hpp!!!**

2023-12-18 18:18 UTC, Sage-Cat approved these changes

2023-12-18 18:18 UTC, merged