Converting QML MainMenu to QWidgets
Sage-Cat/SageStore pull request #6
Opened 2023-12-16 13:51 UTC by momotav

Please review)

2023-12-16 18:33 UTC, DanyloPlotskykh commented on _client/src/Ui/Component/MainMenu.hpp
> +    QAction *exitAction = new QAction("Exit", this);
помоєму краще реалізовувати new в сpp  а не в hpp.(так вроді Володя казав)

2023-12-17 12:57 UTC, Sage-Cat requested changes

2023-12-17 12:57 UTC, Sage-Cat commented on _client/src/Ui/Component/MainMenu.hpp
> +#define MAINMENU_H
`pragma once`, not `ifndef`

2023-12-17 12:57 UTC, Sage-Cat commented on _client/src/Ui/Component/MainMenu.hpp
> +    QMenu *fileMenu = this->addMenu("File");
Make all this properties private

2023-12-17 12:57 UTC, Sage-Cat commented on _client/src/Ui/Component/MainMenu.cpp
> +    purchasingMenu->addAction("Supplier Management");
Don't use hardcoded strings

Use enum-map<enum, string> approach
Create `enum class ActionTypes` with action identificators and use `map<enum, string> ACTION_NAMES` to set names to the menu

2024-03-23 20:47 UTC, closed without merging